### ISSUE TITLE
Some suggestions for pubg ranking scraper

### ISSUE THREAD

**Issue by mzfr** [rao-athar/python-project#1]
* [Here](https://github.com/rao-athar/python-project/blob/main/pubg-allserveranking.py#L16-L32) the major part of the link is the same and the changing part of that link is exactly the same as the argument accepted so rather than having so many if conditions just directly use the user input to modify the URL.
	- See how to use `.format` with strings in python3 and then think.

* Try to use packages like `tabulate` or `prettytable` to print the table.
* Fix all the pep8 issues

Also, try for each point above try to have a different commit. Try to not push everything in a single commit.

**Comment by rao-athar** [comment]
thankyou for your help i followed all your suggestions to write my code in a better way
